---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM template using the new vmware_guest module
- name: Create Blank VM Template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_username: administrator@vsphere.local
    vcenter_password: P@ssw0rd
    vcenter_hostname: 192.168.2.5
    esxi_hostname: 192.168.2.3
    datastore: datastore2
    network: "Non-OCP"
    #vmtemplate: CentOS7-Base
    guest_os_shortname: rhel8_64Guest
    vmcluster: Cluster
    vm_name: rhel8_blank
    notes: Created by Ansible Playbook
    dumpfacts: False
  tasks:
    #- name: Check for required variables
    #  fail: msg="Must pass name and group to -e"
    #  when: name is not defined or group is not defined
    #- name: Check for vSphere access parameters
    #  fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
    #  when: (vcenter_user is not defined) or (vcenter_pass is not defined)
      
    - name: Create Blank VM
      community.vmware.vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        datacenter: Datacenter
        name: "{{ vm_name }}"
        #template: "{{ vmtemplate }}"
        folder: /Datacenter/vm/Templates
        is_template: true
        state: poweredoff
        guest_id: "{{ guest_os_shortname }}"
        disk:
          - size_gb: 10
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          #memory_mb: "{{ vm_memory | default(1024) }}"
          memory_mb: 1024
          num_cpus: 1
          scsi: paravirtual
        networks:
        - name: "{{ network }}"
          device: vmxnet3
        wait_for_ip_address: false
        wait_for_ip_address_timeout: 300
      delegate_to: localhost
      register: newvm
    
    - name: Convert Blank VM to Template
      community.vmware.vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        datacenter: Datacenter
        name: "{{ vm_name }}"
        folder: /Datacenter/vm/Templates
        is_template: true
        state: present      
      delegate_to: localhost
      register: newvm

    #- name: IP address info
    #  debug:
    #    msg: "{{ newvm.instance.ipv4 }} {{ name }}"